-- Create subscribers table
CREATE TABLE IF NOT EXISTS subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    subscribed_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Public can insert subscribers" ON subscribers;
DROP POLICY IF EXISTS "Admins can view subscribers" ON subscribers;
DROP POLICY IF EXISTS "Admins can delete subscribers" ON subscribers;

-- Allow anyone to subscribe (insert)
CREATE POLICY "Public can insert subscribers" 
ON subscribers FOR INSERT 
WITH CHECK (true);

-- Allow admins to view subscribers
CREATE POLICY "Admins can view subscribers" 
ON subscribers FOR SELECT 
USING (
    auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Allow admins to delete subscribers
CREATE POLICY "Admins can delete subscribers" 
ON subscribers FOR DELETE 
USING (
    auth.role() = 'authenticated' AND 
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
