-- Create master_locations table
CREATE TABLE IF NOT EXISTS master_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pincode text NOT NULL,
  city text NOT NULL,
  state text NOT NULL,
  country text DEFAULT 'IN',
  created_at timestamptz DEFAULT now(),
  UNIQUE(pincode)
);

-- Create serviceable_rules table
CREATE TABLE IF NOT EXISTS serviceable_rules (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  rule_type text NOT NULL CHECK (rule_type IN ('state', 'city', 'pincode')),
  value text NOT NULL, -- The actual state name, city name, or pincode
  parent_value text, -- Context: State name for city, City name for pincode (optional but helpful)
  is_allowed boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Create delivery_settings table
CREATE TABLE IF NOT EXISTS delivery_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_city text,
  store_state text,
  store_pincode text,
  store_address text,
  is_all_india_serviceable boolean DEFAULT false,
  updated_at timestamptz DEFAULT now()
);

-- Add initial row for settings if not exists
INSERT INTO delivery_settings (id, is_all_india_serviceable)
SELECT 1, false
WHERE NOT EXISTS (SELECT 1 FROM delivery_settings WHERE id = 1);

-- Modify orders table
ALTER TABLE orders 
ADD COLUMN IF NOT EXISTS delivery_type text CHECK (delivery_type IN ('partner', 'shop', 'pickup')),
ADD COLUMN IF NOT EXISTS delivery_partner_details jsonb, -- { provider, tracking_id, url }
ADD COLUMN IF NOT EXISTS shop_delivery_details jsonb, -- { boy_name, boy_phone, vehicle_no }
ADD COLUMN IF NOT EXISTS pickup_verification_code text,
ADD COLUMN IF NOT EXISTS is_pickup_verified boolean DEFAULT false;

-- RLS Policies
ALTER TABLE master_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE serviceable_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE delivery_settings ENABLE ROW LEVEL SECURITY;

-- Public read access for validations
CREATE POLICY "Public read master_locations" ON master_locations FOR SELECT USING (true);
CREATE POLICY "Public read serviceable_rules" ON serviceable_rules FOR SELECT USING (true);
CREATE POLICY "Public read delivery_settings" ON delivery_settings FOR SELECT USING (true);

-- Admin full access
-- Assuming admin has role 'admin' or checks auth.uid() against an admin table. 
-- For simplicity using public read/write for now or specific authenticated logic if needed. 
-- You might want to restrict WRITE to admins only.
CREATE POLICY "Admin all master_locations" ON master_locations FOR ALL USING (auth.role() = 'authenticated'); -- Refine to admin later
CREATE POLICY "Admin all serviceable_rules" ON serviceable_rules FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Admin all delivery_settings" ON delivery_settings FOR ALL USING (auth.role() = 'authenticated');

-- Seed some logic for master_locations (Example Data)
-- This is just for testing. Real data needs to be imported.
INSERT INTO master_locations (pincode, city, state) VALUES
('411001', 'Pune', 'Maharashtra'),
('411002', 'Pune', 'Maharashtra'),
('411004', 'Pune', 'Maharashtra'),
('400001', 'Mumbai', 'Maharashtra'),
('110001', 'Delhi', 'Delhi')
ON CONFLICT (pincode) DO NOTHING;
